# Generated by Django 4.1.3 on 2022-12-03 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_like_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="email",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emailUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
