# Generated by Django 4.1.3 on 2022-12-03 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_post_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="email",
        ),
    ]
